### ISSUE TITLE
Please remove Google Analytics!

### ISSUE THREAD

**Issue by htgoebel** [kontalk/website#10]
Please revert 2e804986a02ef8a.

It's a contraction that you propose to develop a messenger dedicated to privacy but are using goggle analytics! So using Kontalk may not be tracked, but every visit on you website will. Please remove this.

I have to admit that I'm quite disappoint about this!

If you *really* need to track you visitors (which I doubt to be necessary), use piwik and collect the data in you own servers instead of betraying your visitors to Google.

**Comment by htgoebel** [comment]
Please note: Reverting the commit mentioned above removes Google Analytics only from kontak.org. Kontok.net has the same issue.

**Comment by daniele-athome** [comment]
Strong words you're using @htgoebel. I think we are taking this a bit to the extreme. We use analytics just to collect stats about our web sites which is legal. It could have been any other provider, Google or anyone else. I'm not writing Kontalk to boycott Google.

You know users can disable Google analytics tracking with a browser addon.

**Comment by webratte** [comment]
@htgoebel 
You van use e.g Ghostery ;-)
https://www.ghostery.com/de/download
