### ISSUE TITLE
Please move F-droid logo to the top

### ISSUE THREAD

**Issue by htgoebel** [kontalk/website#11]
You can be proud of you software being available at f-droid, so you should show that and move the logo to the top.

In addition the is increase the visibility of f-droid and show people: There are alternatives to Google Store. AS of now you are doing unpaid promotion for Google only - simply by showing their logo and hiding alternatives at the bottom of your page.

**Comment by daniele-athome** [comment]
Please stop saying such things: I'm not doing unpaid promotion to Google!
Besides, it seems right to put them on the same level.

**Comment by htgoebel** [comment]
Thanks.
