### ISSUE TITLE
Many unused CSS selectors

### ISSUE THREAD

**Issue by XYQuadrat** [kontalk/website#21]
A quick glance at the styles of this site show that there are many unused selectors which only slow down the page and also make it harder to read the code. Chrome reports that "641 rules (84%) of CSS not used by the current page." If nobody has something against it, I would like to remove these.

**Comment by daniele-athome** [comment]
Are you referring to kontalk.net or kontalk.org?

**Comment by XYQuadrat** [comment]
Both. The 641 rules are from kontalk.org, but kontalk.net has about the same number of obsolete selectors.

**Comment by daniele-athome** [comment]
I think those are mainly from [Bootstrap](https://getbootstrap.com). If you want you can build a custom version of Bootstrap [right from their website](http://getbootstrap.com/customize/), it'll be great if you do it and request a pull. Please refrain from manually removing classes from the CSS directly and also be sure to include the configuration file exported from the Bootstrap site (config.json) so it can be reused for upgrades. Thanks!! :-)

**Comment by XYQuadrat** [comment]
Going to do that in the next few days.

**Comment by daniele-athome** [comment]
Fixed by #22.
